# Generated by Django 5.0.6 on 2024-06-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_category_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
