# Generated by Django 5.0.6 on 2024-06-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="username",
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
