# Generated by Django 5.0.6 on 2024-06-11 22:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_client_managers_alter_client_is_staff_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="username",
        ),
    ]
