# Generated by Django 5.0.6 on 2024-07-02 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_initial"),
        ("users", "0002_userproxy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="users.userproxy"
            ),
        ),
    ]
