# Generated by Django 5.0.6 on 2024-07-13 20:20

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.products.models.user_directory_path),  # noqa: E501
        ),
    ]
